# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "Upcoming Activities"
pageRef = "upcoming_activities"
weight = 20

[[main]]
name = "Expository Talks (New!)"
parent = "Upcoming Activities"
pageRef = "upcoming_activities/expository_talks"
weight = 20

[[main]]
name = "News and Events"
parent = "Upcoming Activities"
pageRef = "upcoming_activities/news_and_events"
weight = 20

[[main]]
name = "Participate"
pageRef = "participate"
weight = 20

[[main]]
name = "Submit Problem"
parent = "Participate"
pageRef = "participate/submit_problem"
weight = 20

[[main]]
name = "Submit Articles"
parent = "Participate"
pageRef = "participate/submit_articles_and_notes"
weight = 20

[[main]]
name = "Present Talks"
parent = "Participate"
pageRef = "participate/present_talks"
weight = 20

[[main]]
name = "Submit Doubts"
parent = "Participate"
pageRef = "participate/submit_doubts"
weight = 20

[[main]]
name = "Resources"
pageRef = "resources"
weight = 20

[[main]]
name = "Additional References"
parent = "Resources"
pageRef = "resources/additional_resources"
weight = 20

[[main]]
name = "Some Fun Puzzles"
parent = "Resources"
pageRef = "resources/fun_puzzles"
weight = 20

[[main]]
name = "General Problems"
parent = "Resources"
pageRef = "resources/general_problems"
weight = 20

[[main]]
name = "Articles"
parent = "Resources"
pageRef = "resources/archived_articles"
weight = 20

[[main]]
name = "Past Activities"
pageRef = "past_activities"
weight = 20

[[main]]
name = "Foundational Courses"
parent = "Past Activities"
pageRef = "past_activities/foundational_courses"
weight = 20

[[main]]
name = "Lecture Series"
parent = "Past Activities"
pageRef = "past_activities/lecture_series"
weight = 20

[[main]]
name = "Expository Talks"
parent = "Past Activities"
pageRef = "past_activities/expository_talks"
weight = 20

[[main]]
name = "UDGRP"
parent = "Past Activities"
pageRef = "udgrp"
weight = 20

[[main]]
name = "WMOU"
parent = "Past Activities"
pageRef = "wmou"
weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

[[footer]]
name = "Participate"
pageRef = "participate"
weight = 2

[[footer]]
name = "Events"
pageRef = "news_and_events"
weight = 3

[[footer]]
name = "Mailing List"
url = "https://forms.gle/13cXVcVySETrEv8W7"
weight = 1
